import type { NextPage } from "next";
import Head from "next/head";
import { Grid, Typography } from "@mui/material";
import { SportButton } from "@components/SportButton/SportButton";
import { SportLink } from "@components/SportLink/SportLink";
import { MainLayout } from "@features/MainLayout/MainLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Typography variant={"h1"}>H1</Typography>
        <Typography variant={"h2"}>H2</Typography>
        <Typography variant={"h3"}>H3</Typography>
        <Typography variant={"h4"}>H4</Typography>
        <Typography variant={"h5"}>H5</Typography>
        <Typography variant={"h6"}>H6</Typography>
        <Typography variant={"body1"}>Body1</Typography>
        <Typography variant={"body2"}>Body2</Typography>
        <Typography variant={"subtitle1"}>Subtitle1</Typography>
        <Typography variant={"subtitle2"}>Subtitle2</Typography>
        <Typography variant={"overline"}>Overline</Typography>
        <Grid>
          <SportButton>Contained</SportButton>
          <SportButton variant={"outlined"}>Outlined</SportButton>
          <SportButton variant={"text"}>Text</SportButton>
          <SportLink to={"/"}>Link</SportLink>
        </Grid>
      </MainLayout>
    </>
  );
};

export default Home;
