import type { NextPage } from "next";
import Head from "next/head";

import { motion } from "framer-motion";
import { Grid } from "@mui/material";

import { SportButton } from "@shared/ui/SportButton/SportButton";
import { SportLink } from "@shared/ui/SportLink/SportLink";

import { MainLayout } from "@layouts/MainLayout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <h1>H1</h1>
        <h2>H2</h2>
        <h3>H3</h3>
        <h4>H4</h4>
        <h5>H5</h5>
        <motion.h6
          drag
          dragConstraints={{ left: 0, right: 0, top: 0, bottom: 0 }}
        >
          H6
        </motion.h6>
        <p>
          <motion.span initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. A
            accusamus corporis, cum dolore excepturi illum iure labore
            laudantium nesciunt, nisi non numquam odio perferendis porro quidem,
            reiciendis rerum sed vero.
          </motion.span>
        </p>
        <Grid>
          <SportButton>Contained</SportButton>
          <SportButton variant={"outlined"}>Outlined</SportButton>
          <SportButton variant={"text"}>Text</SportButton>
          <SportLink to={"/"}>Link</SportLink>
        </Grid>
      </MainLayout>
    </>
  );
};

export default Home;
