version: "3.9"
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"
  rabbit:
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=pass
    restart: on-failure
    ports:
    - "15672:15672"
    - "5672:5672"
  identity:
    image: diplom_identity
    depends_on:
      - sqldb
      - rabbit
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
  gateway:
    image: gateway
    depends_on:
      - identity
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "6000:80"
  userflow:
     image: userflow
     depends_on:
      - gateway
     restart: on-failure
     environment:
      - ASPNETCORE_ENVIRONMENT=Production
     ports:
      - "7000:80"
  message:
      image: messageservice
      depends_on:
       - rabbit
      restart: on-failure
      environment:
       - ASPNETCORE_ENVIRONMENT=Production
      ports:
       - "8000:80"