// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserWorkflow.Images;

#nullable disable

namespace UserWorkflow.Images.Migrations
{
    [DbContext(typeof(ImagesDataContext))]
    partial class ImagesDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UserWorkflow.Images.Models.DomainImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DomainImages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DomainImage");
                });

            modelBuilder.Entity("UserWorkflow.Images.Models.ExerciseImage", b =>
                {
                    b.HasBaseType("UserWorkflow.Images.Models.DomainImage");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ExerciseImage");
                });

            modelBuilder.Entity("UserWorkflow.Images.Models.FoodImage", b =>
                {
                    b.HasBaseType("UserWorkflow.Images.Models.DomainImage");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("FoodImage");
                });

            modelBuilder.Entity("UserWorkflow.Images.Models.UserImage", b =>
                {
                    b.HasBaseType("UserWorkflow.Images.Models.DomainImage");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("UserImage");
                });
#pragma warning restore 612, 618
        }
    }
}
