name: Deployment workflow
on: workflow_dispatch
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Compose
        run: |
          docker-compose build
          docker-compose push
  restarting_dockercompose:
    needs: build_push
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: connecting to droplet via ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: e-sport.cloud
          username: root
          key: ${{secrets.ESPORT_ACTION_SECRET}}
          port: 22
          script: whoami
